train:
  _target_: src.datasets.LJSpeechDataset
  audio_dir: "LJSpeech"
  limit: 1
val:
  _target_: src.datasets.CustomDirDataset
  transcription_dir: "LJSpeech"
  limit: 1
test:
  _target_: src.datasets.LJSpeechDataset
  audio_dir: "test_data"