train:
  _target_: src.datasets.LJSpeechDataset
  audio_dir: "LJSpeech"
  limit: 1
  instance_transforms: ${transforms.instance_transforms.train}
val:
  _target_: src.datasets.CustomDirDataset
  transcription_dir: "LJSpeech"
  limit: 1

