train: 
  - _target_: src.metrics.MOS
    name: "MOS" # metrics that are calculated during training
inference: 
  - _target_: src.metrics.MOS
    name: "MOS" # metrics that are calculated during training