train:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  num_workers: 2
  pin_memory: True
val:
  _target_: torch.utils.data.DataLoader
  batch_size: 5
  num_workers: 2
  pin_memory: True
test:
  _target_: torch.utils.data.DataLoader
  batch_size: 5
  num_workers: 2
  pin_memory: True
